server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lcsousa/microservice-repo
          search-paths: security
          
  
  
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: E:/microservice-repo

